version: "1.0"
info:
  model: int-scaffold
packages:
- name: Ser_GH_0708Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: upperfspackage
  version: "1.0"
  gitServerName: srcCtrl_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artikhare
  gitBranch: master
services:
- serviceName: project.ser_gh_0708.integrations:bitbucketfs
  packages:
  - name: Ser_GH_0708Project
    version: "1.0"
  - name: upperfspackage
    version: "1.0"
- serviceName: UpperFSPackage:upperfs
  packages:
  - name: upperfspackage
    version: "1.0"
- serviceName: pub.string:toUpper
  packages:
  - name: WmPublic
    version: 11.1.0.0.2074
